// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

// scanEnum provides generic scanning logic for enum types.
// It handles nil, int64, string, []byte, and various pointer types.
func scanEnum[T any](x *T, zero T, parse func(string) (T, error), errNilPtr error, value interface{}) (err error) {
	if value == nil {
		*x = zero
		return
	}

	switch v := value.(type) {
	case int64:
		*x = zero
	case string:
		*x, err = parse(v)
	case []byte:
		*x, err = parse(string(v))
	case T:
		*x = v
	case int:
		*x = zero
	case *T:
		if v == nil {
			return errNilPtr
		}
		*x = *v
	case uint:
		*x = zero
	case uint64:
		*x = zero
	case *int:
		if v == nil {
			return errNilPtr
		}
		*x = zero
	case *int64:
		if v == nil {
			return errNilPtr
		}
		*x = zero
	case float64:
		*x = zero
	case *float64:
		if v == nil {
			return errNilPtr
		}
		*x = zero
	case *uint:
		if v == nil {
			return errNilPtr
		}
		*x = zero
	case *uint64:
		if v == nil {
			return errNilPtr
		}
		*x = zero
	case *string:
		if v == nil {
			return errNilPtr
		}
		*x, err = parse(*v)
	}

	return
}

const (
	// ActorKindUser is a ActorKind of type User.
	ActorKindUser ActorKind = iota
	// ActorKindBot is a ActorKind of type Bot.
	ActorKindBot
	// ActorKindSystem is a ActorKind of type System.
	ActorKindSystem
	// ActorKindService is a ActorKind of type Service.
	ActorKindService
)

var ErrInvalidActorKind = fmt.Errorf("not a valid ActorKind, try [%s]", strings.Join(_ActorKindNames, ", "))

const _ActorKindName = "UserBotSystemService"

var _ActorKindNames = []string{
	_ActorKindName[0:4],
	_ActorKindName[4:7],
	_ActorKindName[7:13],
	_ActorKindName[13:20],
}

// ActorKindNames returns a list of possible string values of ActorKind.
func ActorKindNames() []string {
	tmp := make([]string, len(_ActorKindNames))
	copy(tmp, _ActorKindNames)
	return tmp
}

// ActorKindValues returns a list of the values for ActorKind
func ActorKindValues() []ActorKind {
	return []ActorKind{
		ActorKindUser,
		ActorKindBot,
		ActorKindSystem,
		ActorKindService,
	}
}

var _ActorKindMap = map[ActorKind]string{
	ActorKindUser:    _ActorKindName[0:4],
	ActorKindBot:     _ActorKindName[4:7],
	ActorKindSystem:  _ActorKindName[7:13],
	ActorKindService: _ActorKindName[13:20],
}

// String implements the Stringer interface.
func (x ActorKind) String() string {
	return enumString(uint8(x), map[int]string{
		int(ActorKindUser):    _ActorKindName[0:4],
		int(ActorKindBot):     _ActorKindName[4:7],
		int(ActorKindSystem):  _ActorKindName[7:13],
		int(ActorKindService): _ActorKindName[13:20],
	}, "ActorKind")
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActorKind) IsValid() bool {
	_, ok := _ActorKindMap[x]
	return ok
}

var _ActorKindValue = map[string]ActorKind{
	_ActorKindName[0:4]:   ActorKindUser,
	_ActorKindName[4:7]:   ActorKindBot,
	_ActorKindName[7:13]:  ActorKindSystem,
	_ActorKindName[13:20]: ActorKindService,
}

// ParseActorKind attempts to convert a string to a ActorKind.
func ParseActorKind(name string) (ActorKind, error) {
	if x, ok := _ActorKindValue[name]; ok {
		return x, nil
	}
	return ActorKind(0), fmt.Errorf("%s is %w", name, ErrInvalidActorKind)
}

// MarshalText implements the text marshaller method.
func (x ActorKind) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActorKind) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseActorKind(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ActorKind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errActorKindNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ActorKind) Scan(value interface{}) error {
	return scanEnum(x, ActorKind(0), ParseActorKind, errActorKindNilPtr, value)
}

// Value implements the driver Valuer interface.
func (x ActorKind) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// CauseKindDirect is a CauseKind of type Direct.
	// Direct causal relationship
	CauseKindDirect CauseKind = iota
	// CauseKindCommand is a CauseKind of type Command.
	// Command-triggered relationship
	CauseKindCommand
	// CauseKindEvent is a CauseKind of type Event.
	// Event-triggered relationship
	CauseKindEvent
)

var ErrInvalidCauseKind = fmt.Errorf("not a valid CauseKind, try [%s]", strings.Join(_CauseKindNames, ", "))

const _CauseKindName = "DirectCommandEvent"

var _CauseKindNames = []string{
	_CauseKindName[0:6],
	_CauseKindName[6:13],
	_CauseKindName[13:18],
}

// CauseKindNames returns a list of possible string values of CauseKind.
func CauseKindNames() []string {
	tmp := make([]string, len(_CauseKindNames))
	copy(tmp, _CauseKindNames)
	return tmp
}

// CauseKindValues returns a list of the values for CauseKind
func CauseKindValues() []CauseKind {
	return []CauseKind{
		CauseKindDirect,
		CauseKindCommand,
		CauseKindEvent,
	}
}

var _CauseKindMap = map[CauseKind]string{
	CauseKindDirect:  _CauseKindName[0:6],
	CauseKindCommand: _CauseKindName[6:13],
	CauseKindEvent:   _CauseKindName[13:18],
}

// String implements the Stringer interface.
func (x CauseKind) String() string {
	return enumString(uint8(x), map[int]string{
		int(CauseKindDirect):  _CauseKindName[0:6],
		int(CauseKindCommand): _CauseKindName[6:13],
		int(CauseKindEvent):   _CauseKindName[13:18],
	}, "CauseKind")
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CauseKind) IsValid() bool {
	_, ok := _CauseKindMap[x]
	return ok
}

var _CauseKindValue = map[string]CauseKind{
	_CauseKindName[0:6]:   CauseKindDirect,
	_CauseKindName[6:13]:  CauseKindCommand,
	_CauseKindName[13:18]: CauseKindEvent,
}

// ParseCauseKind attempts to convert a string to a CauseKind.
func ParseCauseKind(name string) (CauseKind, error) {
	if x, ok := _CauseKindValue[name]; ok {
		return x, nil
	}
	return CauseKind(0), fmt.Errorf("%s is %w", name, ErrInvalidCauseKind)
}

// MarshalText implements the text marshaller method.
func (x CauseKind) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CauseKind) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseCauseKind(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *CauseKind) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errCauseKindNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *CauseKind) Scan(value interface{}) error {
	return scanEnum(x, CauseKind(0), ParseCauseKind, errCauseKindNilPtr, value)
}

// Value implements the driver Valuer interface.
func (x CauseKind) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// PriorityLow is a Priority of type Low.
	PriorityLow Priority = iota
	// PriorityMedium is a Priority of type Medium.
	PriorityMedium
	// PriorityHigh is a Priority of type High.
	PriorityHigh
	// PriorityCritical is a Priority of type Critical.
	PriorityCritical
)

var ErrInvalidPriority = fmt.Errorf("not a valid Priority, try [%s]", strings.Join(_PriorityNames, ", "))

const _PriorityName = "LowMediumHighCritical"

var _PriorityNames = []string{
	_PriorityName[0:3],
	_PriorityName[3:9],
	_PriorityName[9:13],
	_PriorityName[13:21],
}

// PriorityNames returns a list of possible string values of Priority.
func PriorityNames() []string {
	tmp := make([]string, len(_PriorityNames))
	copy(tmp, _PriorityNames)
	return tmp
}

// PriorityValues returns a list of the values for Priority
func PriorityValues() []Priority {
	return []Priority{
		PriorityLow,
		PriorityMedium,
		PriorityHigh,
		PriorityCritical,
	}
}

var _PriorityMap = map[Priority]string{
	PriorityLow:      _PriorityName[0:3],
	PriorityMedium:   _PriorityName[3:9],
	PriorityHigh:     _PriorityName[9:13],
	PriorityCritical: _PriorityName[13:21],
}

// String implements the Stringer interface.
func (x Priority) String() string {
	return enumString(uint8(x), map[int]string{
		int(PriorityLow):      _PriorityName[0:3],
		int(PriorityMedium):   _PriorityName[3:9],
		int(PriorityHigh):     _PriorityName[9:13],
		int(PriorityCritical): _PriorityName[13:21],
	}, "Priority")
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Priority) IsValid() bool {
	_, ok := _PriorityMap[x]
	return ok
}

var _PriorityValue = map[string]Priority{
	_PriorityName[0:3]:   PriorityLow,
	_PriorityName[3:9]:   PriorityMedium,
	_PriorityName[9:13]:  PriorityHigh,
	_PriorityName[13:21]: PriorityCritical,
}

// ParsePriority attempts to convert a string to a Priority.
func ParsePriority(name string) (Priority, error) {
	if x, ok := _PriorityValue[name]; ok {
		return x, nil
	}
	return Priority(0), fmt.Errorf("%s is %w", name, ErrInvalidPriority)
}

// MarshalText implements the text marshaller method.
func (x Priority) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Priority) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParsePriority(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Priority) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errPriorityNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Priority) Scan(value interface{}) error {
	return scanEnum(x, Priority(0), ParsePriority, errPriorityNilPtr, value)
}

// Value implements the driver Valuer interface.
func (x Priority) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// StatusDraft is a Status of type Draft.
	StatusDraft Status = iota
	// StatusActive is a Status of type Active.
	StatusActive
	// StatusPaused is a Status of type Paused.
	StatusPaused
	// StatusArchived is a Status of type Archived.
	StatusArchived
	// StatusDeleted is a Status of type Deleted.
	StatusDeleted
)

var ErrInvalidStatus = fmt.Errorf("not a valid Status, try [%s]", strings.Join(_StatusNames, ", "))

const _StatusName = "DraftActivePausedArchivedDeleted"

var _StatusNames = []string{
	_StatusName[0:5],
	_StatusName[5:11],
	_StatusName[11:17],
	_StatusName[17:25],
	_StatusName[25:32],
}

// StatusNames returns a list of possible string values of Status.
func StatusNames() []string {
	tmp := make([]string, len(_StatusNames))
	copy(tmp, _StatusNames)
	return tmp
}

// StatusValues returns a list of the values for Status
func StatusValues() []Status {
	return []Status{
		StatusDraft,
		StatusActive,
		StatusPaused,
		StatusArchived,
		StatusDeleted,
	}
}

var _StatusMap = map[Status]string{
	StatusDraft:    _StatusName[0:5],
	StatusActive:   _StatusName[5:11],
	StatusPaused:   _StatusName[11:17],
	StatusArchived: _StatusName[17:25],
	StatusDeleted:  _StatusName[25:32],
}

// String implements the Stringer interface.
func (x Status) String() string {
	return enumString(uint8(x), map[int]string{
		int(StatusDraft):    _StatusName[0:5],
		int(StatusActive):   _StatusName[5:11],
		int(StatusPaused):   _StatusName[11:17],
		int(StatusArchived): _StatusName[17:25],
		int(StatusDeleted):  _StatusName[25:32],
	}, "Status")
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, ok := _StatusMap[x]
	return ok
}

var _StatusValue = map[string]Status{
	_StatusName[0:5]:   StatusDraft,
	_StatusName[5:11]:  StatusActive,
	_StatusName[11:17]: StatusPaused,
	_StatusName[17:25]: StatusArchived,
	_StatusName[25:32]: StatusDeleted,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(0), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Status) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Status) Scan(value interface{}) error {
	return scanEnum(x, Status(0), ParseStatus, errStatusNilPtr, value)
}

// Value implements the driver Valuer interface.
func (x Status) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// TriggerManual is a Trigger of type Manual.
	// Direct user action
	TriggerManual Trigger = iota
	// TriggerScheduled is a Trigger of type Scheduled.
	// Time-based trigger (cron, delay)
	TriggerScheduled
	// TriggerWebhook is a Trigger of type Webhook.
	// External system via webhook
	TriggerWebhook
	// TriggerImport is a Trigger of type Import.
	// Bulk data import
	TriggerImport
	// TriggerMigration is a Trigger of type Migration.
	// Data migration
	TriggerMigration
	// TriggerSystem is a Trigger of type System.
	// Automatic system action
	TriggerSystem
	// TriggerCorrection is a Trigger of type Correction.
	// Correction of previous data
	TriggerCorrection
)

var ErrInvalidTrigger = fmt.Errorf("not a valid Trigger, try [%s]", strings.Join(_TriggerNames, ", "))

const _TriggerName = "ManualScheduledWebhookImportMigrationSystemCorrection"

var _TriggerNames = []string{
	_TriggerName[0:6],
	_TriggerName[6:15],
	_TriggerName[15:22],
	_TriggerName[22:28],
	_TriggerName[28:37],
	_TriggerName[37:43],
	_TriggerName[43:53],
}

// TriggerNames returns a list of possible string values of Trigger.
func TriggerNames() []string {
	tmp := make([]string, len(_TriggerNames))
	copy(tmp, _TriggerNames)
	return tmp
}

// TriggerValues returns a list of the values for Trigger
func TriggerValues() []Trigger {
	return []Trigger{
		TriggerManual,
		TriggerScheduled,
		TriggerWebhook,
		TriggerImport,
		TriggerMigration,
		TriggerSystem,
		TriggerCorrection,
	}
}

var _TriggerMap = map[Trigger]string{
	TriggerManual:     _TriggerName[0:6],
	TriggerScheduled:  _TriggerName[6:15],
	TriggerWebhook:    _TriggerName[15:22],
	TriggerImport:     _TriggerName[22:28],
	TriggerMigration:  _TriggerName[28:37],
	TriggerSystem:     _TriggerName[37:43],
	TriggerCorrection: _TriggerName[43:53],
}

// String implements the Stringer interface.
func (x Trigger) String() string {
	return enumString(uint8(x), map[int]string{
		int(TriggerManual):     _TriggerName[0:6],
		int(TriggerScheduled):  _TriggerName[6:15],
		int(TriggerWebhook):    _TriggerName[15:22],
		int(TriggerImport):     _TriggerName[22:28],
		int(TriggerMigration):  _TriggerName[28:37],
		int(TriggerSystem):     _TriggerName[37:43],
		int(TriggerCorrection): _TriggerName[43:53],
	}, "Trigger")
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Trigger) IsValid() bool {
	_, ok := _TriggerMap[x]
	return ok
}

var _TriggerValue = map[string]Trigger{
	_TriggerName[0:6]:   TriggerManual,
	_TriggerName[6:15]:  TriggerScheduled,
	_TriggerName[15:22]: TriggerWebhook,
	_TriggerName[22:28]: TriggerImport,
	_TriggerName[28:37]: TriggerMigration,
	_TriggerName[37:43]: TriggerSystem,
	_TriggerName[43:53]: TriggerCorrection,
}

// ParseTrigger attempts to convert a string to a Trigger.
func ParseTrigger(name string) (Trigger, error) {
	if x, ok := _TriggerValue[name]; ok {
		return x, nil
	}
	return Trigger(0), fmt.Errorf("%s is %w", name, ErrInvalidTrigger)
}

// MarshalText implements the text marshaller method.
func (x Trigger) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Trigger) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseTrigger(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Trigger) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errTriggerNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Trigger) Scan(value interface{}) error {
	return scanEnum(x, Trigger(0), ParseTrigger, errTriggerNilPtr, value)
}

// Value implements the driver Valuer interface.
func (x Trigger) Value() (driver.Value, error) {
	return x.String(), nil
}
