# go-composable-business-types - Build and test commands
# Generated by Crush - use 'just' to run commands

# Default recipe - show help
default:
    @just --list

# Generate enum code
generate:
    GOEXPERIMENT=jsonv2 go generate ./...

# Build the project
build:
    GOEXPERIMENT=jsonv2 go build ./...

# Run all tests with race detector
test:
    GOEXPERIMENT=jsonv2 go test -race ./...

# Run tests with coverage
test-coverage:
    GOEXPERIMENT=jsonv2 go test -race -coverprofile=coverage.out ./...
    @go tool cover -func=coverage.out | grep -E '^total:'

# Run benchmarks
bench:
    GOEXPERIMENT=jsonv2 go test -bench=. -benchmem -timeout=5m ./...

# Run linting
lint:
    GOEXPERIMENT=jsonv2 golangci-lint run --fix

# Run everything: generate, build, test, lint
check: generate build test lint
    @echo "All checks passed!"

# Clean build artifacts
clean:
    rm -f coverage.out
    go clean -cache

# Show coverage report in browser
coverage-report: test-coverage
    @go tool cover -html=coverage.out

# Install development dependencies
install-deps:
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# Format code
fmt:
    GOEXPERIMENT=jsonv2 go fmt ./...

# Vet code
vet:
    GOEXPERIMENT=jsonv2 go vet ./...

# Run go mod tidy
tidy:
    go mod tidy